### ISSUE TITLE
bug on mercuryo that dosnt allow transactions on BUSD_ BEP20

### ISSUE THREAD

**Issue by draczer01** [onramper/widget#60]
when BUSD is selected using the BEP20 option on mercuryo the url generated by coinpayments dosnt work since it uses an invalid `&currency`, changing `&currency=BUSD_BEP20` to `&currency=BUSD` in the url fixes the problem

**Comment by ProficientSystems** [comment]
I'm having this issue too, that param is simply not being passed on to the Mercury URL

**Comment by vimoppa** [comment]
Thanks for reporting @draczer01 @ProficientSystems, this bug has been fixed.

**Comment by vimoppa** [comment]
@draczer01 can you provide more information so we can reproduce the issue, if you're using the widget package I suggest updating to the latest version.

**Comment by draczer01** [comment]
@vimoppa you will see it clearly if you use this URL: https://widget.onramper.com/?defaultFiat=USD&defaultAmount=50&apiKey=pk_prod_WxFAaPfsX958K9ND_033RyC6G88vmCAsr5vpKBQ5CWE0&onlyCryptos=BUSD_bep20&partnerContext=%7B%22userId%22%3A1%7D&wallets=BUSD:0x7271a83d907272444e83415bc547b1c475f7d1fb&isAmountEditable=false&isAddressEditable=false

**Comment by draczer01** [comment]
![imagen](https://user-images.githubusercontent.com/31465304/158664244-3abcb2eb-ddb7-4253-9865-81032d848475.png)
when you get redirected to that page on mercurio and it is forcing you to buy btc instead of BUSD, this happens because you get a popup of this window:
https://exchange.mercuryo.io/?widget_id=d9c6c6f9-79a1-49dc-8154-b3b52576f58f&type=buy&amount=50&fix_fiat_amount=true&fix_amount=true&currency=BUSD_BEP20&fix_currency=true&fiat_currency=USD&fix_fiat_currency=true&merchant_transaction_id=nz59hdhg9CdlcmgS6HzOgw--&address=0x7271a83d907272444e83415bc547b1c475f7d1fb&hide_address=true&signature=2da30f790db94724aee2d9be281c47792ce8e754291bf76ff150fe4bc765a48a97e589822b4f290e212229332dc2826dafb98ab0d6dff9c75aaae673fb204052

instead of this one: 

https://exchange.mercuryo.io/?widget_id=d9c6c6f9-79a1-49dc-8154-b3b52576f58f&type=buy&amount=50&fix_fiat_amount=true&fix_amount=true&currency=BUSD&fix_currency=true&fiat_currency=USD&fix_fiat_currency=true&merchant_transaction_id=nz59hdhg9CdlcmgS6HzOgw--&address=0x7271a83d907272444e83415bc547b1c475f7d1fb&hide_address=true&signature=2da30f790db94724aee2d9be281c47792ce8e754291bf76ff150fe4bc765a48a97e589822b4f290e212229332dc2826dafb98ab0d6dff9c75aaae673fb204052


which looks like this:

![imagen](https://user-images.githubusercontent.com/31465304/158664742-99e6900b-ffc0-4b6f-9c03-5c4527c73e27.png)

**Comment by vimoppa** [comment]
@draczer01 Thanks, should be fixed now.

**Comment by draczer01** [comment]
thanks, it works now
