### ISSUE TITLE
auto-redirect not working

### ISSUE THREAD

**Issue by TejaDroid** [onramper/widget#68]
I'm trying to integrate a widget using a URL with a test key in Flutter Webview App. The app could not redirect to Url and did not even get close to the external window of the gateway (example - Moonpay) after a successful transaction.

**Comment by nyshthefantastic** [comment]
Hi @TejaDroid this issue has been since resolved.

**Comment by nyshthefantastic** [comment]
Closing this as an inactive issue @TejaDroid
