### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by aliveli186** [onramper/widget#86]
Access to fetch at 'https://onramper.tech/rate/TRY/ETH/creditCard/1800?country=tr&amountInCrypto=false&includeIcons=true&minAmountEur=0' from origin 'https://widget.onramper.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

**Comment by nyshthefantastic** [comment]
Hi @aliveli186 This issue has since been resolved

**Comment by nyshthefantastic** [comment]
Closing this as an inactive issue @TejaDroid
