### ISSUE TITLE
transaction failed due to unexpected reasons 

### ISSUE THREAD

**Issue by snigdha920** [onramper/widget#92]
I'm using the iframe option in a React, NextJS application. 
Here's how I've configured the onramper widget:
```
// --- Configuration ---
const params = [
    `defaultAmount=${donationAmount}`,
    `apiKey=pk_test_x5M_5fdXzn1fxK04seu0JgFjGsu7CH8lOvS9xZWzuSM0`,
    `defaultCrypto=BNB`,
    'wallets=BNB:0x8eD7776E81dB21760627E68123eFD0d6e484F22A',
    'isAmountEditable=false',
    'isAddressEditable=false',
  ];
  
  // --- Component ---
  <iframe
      id="onRamper"
      src={`https://widget.onramper.com?${params.join('&')}`}
      height="600px"
      width="700px"
      title="Onramper widget"
      frameBorder="0"
      allow="accelerometer;autoplay; camera; gyroscope; payment"
      style={{ boxShadow: '1px 1px 1px 1px rgba(0,0,0,0.2)', margin: 'auto' }}
    >
      <a href="https://widget.onramper.com" rel="noreferrer" target="_blank">
        Buy crypto
      </a>
    </iframe>
```

On the last step, in the purchase view, after entering the test card details for Moonpay 
I get a "Transaction has failed error due to unexpected reasons". error:
<img width="1552" alt="Screenshot 2022-03-16 at 9 14 33 AM" src="https://user-images.githubusercontent.com/62167899/158513072-93f49fbe-38c3-46d4-954d-312f87707a34.png">

Here's the details of my transaction after entering the code from the email:
<img width="1552" alt="Screenshot 2022-03-16 at 9 14 12 AM" src="https://user-images.githubusercontent.com/62167899/158513127-81aab0ea-6488-4566-b642-9d01d58dea67.png">

And here's the error I see in the network tab: 
<img width="1552" alt="Screenshot 2022-03-16 at 9 14 48 AM" src="https://user-images.githubusercontent.com/62167899/158513163-61ac03a7-3e7d-450e-8146-c8e3b98436e3.png">

This is odd because my wallet address `0x8eD7776E81dB21760627E68123eFD0d6e484F22A` is correct, I have double checked multiple times. 

More context: I am based out of India, so my country is IN. 

I need to resolve this issue urgently, I don't know how, any help would be very appreciated.

**Comment by vimoppa** [comment]
@snigdha920 your address `0x8eD7776E81dB21760627E68123eFD0d6e484F22A` is a valid for `BNB_BEP20`.

You can check the validity by sending a request to our endpoint.

`https://onramper.tech/address/BNB_BEP20/0x8eD7776E81dB21760627E68123eFD0d6e484F22A`
```json
{
    "valid": true
}
```
